name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Build zip
        run: make build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: "*.zip"
          generate_release_notes: true
